env: local # env: APP_ENV
debug: true # env: APP_DEBUG
locale: zh-CN # env: APP_LOCALE
key: somerandomkey!!! #aes encryption key either 16, 24, or 32 bytes to select, env: APP_KEY
timezone: Asia/Shanghai # env: APP_TIMEZONE