default: mysql # env: DB_CONNECTION
connections:
  mysql:
    driver: mysql
    dsn: root:root@tcp(127.0.0.1:3306)/enorith?charset=utf8mb4&parseTime=True&loc=Local #env: DB_DSN
  oracle:
    driver: oracle
    dsn: oracle://username:password@host:port/db
implicit_injection: true
# migrate table
migrate: true
log_channel: database