default: default
channels: 
  default:
    outputs:
      - rotate:///runtime.log # schema supports: rotate, single, file, stdout, stderr
  single:
    outputs:
      - single:///runtime.log
  http:
    outputs:
      - rotate:///http.log
  http_error:
    outputs:
      - rotate:///http.error.log
  database:
    outputs:
      - rotate:///database.log