default: default # env: LOGGING_CHANNEL
channels: 
  default:
    outputs:
      - rotate:///runtime.log?limit=15 # schema supports: rotate, single, file, stdout, stderr
      - stdout
  single:
    outputs:
      - single:///runtime.log
  http:
    outputs:
      - rotate:///http/http.log?limit=15
      - stdout
    label: http
  database:
    outputs:
      - rotate:///database/database.log?limit=15