listen: true
connection: mem
running_workers:
  - default
  
workers:
  default:
    connection: mem
    concurrency: 4
  nsq:
    connection: nsq
    concurrency: 4

connections:
  nsq:
    driver: nsq # support: nsq, mem
    config:
      nsqd: localhost:4150 # env: QUEUE_NSQD
  mem:
    driver: mem