listen: true
connection: mem
running_workers:
  - default
  
workers:
  default:
    connection: mem
    concurrency: 4
  nsq:
    connection: nsq
    concurrency: 4

connections:
  nsq:
    driver: nsq # support: nsq, mem
    config:
      nsqd: 127.0.0.1:49157 # env: QUEUE_NSQD
      #nsqlookupd: localhost:4161 # env: QUEUE_NSQLOOKUPD
  mem:
    driver: mem