default: default # env:REDIS_CONNECTION
connections:
  default:
    addrs:
      - 127.0.0.1:6379
    database: 0
  cache:
    addrs:
      - 127.0.0.1:6379
    database: 1
  session:
    addrs:
      - 127.0.0.1:6379
    database: 2
  queue:
    addrs:
      - 127.0.0.1:6379
    database: 3